### ISSUE TITLE
Java Concurrency

### ISSUE THREAD

**Issue by XueqiangChen** [XueqiangChen/java-basic#3]

**Comment by XueqiangChen** [comment]
Java创建线程的方式有多少种？分别写出每一种创建方式。

```
代码提交到一下目录：
java-basic
    - learning-java
        - src
```

> 注意事项：提交代码的时候请加上注释，例如：
`git commit -m "#3 第一次添加"`
内容中 #3 是issue的编号，必须填写才能关联到issue。

**Comment by yxg188** [comment]
# 2019年5月2日
## Done

1. 提交代码到issue

## Todo

1. xxx

**Comment by yxg188** [comment]
学习完多线程

**Comment by yxg188** [comment]
2019年5月4号
Done
学习完多线程

**Comment by XueqiangChen** [comment]
@yxg188 每天的任务那里要写一下具体的内容，例如多线程学习了哪些内容？再写一下后一天的安排

**Comment by XueqiangChen** [comment]
@yxg188 这个issue的代码今天完成一下

**Comment by XueqiangChen** [comment]
[Java多线程面试题](http://www.importnew.com/12773.html)
