### ISSUE TITLE
Daily Task

### ISSUE THREAD

**Issue by yxg188** [XueqiangChen/java-basic#6]

**Comment by yxg188** [comment]
2019年5月4号
Done
1.学习完多线程

**Comment by XueqiangChen** [comment]
# 2019年5月5日
## Todo
1. review controller loop in think-in-java 
2. review code of concurrency

**Comment by yxg188** [comment]
2019年5月5号

done

1.提交了三个多线程的方式的issue并修改了错误。
2学习了线程池的三种方法。
3学习了多线程的优先级。

**Comment by XueqiangChen** [comment]
> 2019年5月5号
> 
> done
> 
> 1.提交了三个多线程的方式的issue并修改了错误。
> 2学习了线程池的三种方法。
> 3学习了多线程的优先级。

第二个是说学习了创建线程的三种方法吗？

**Comment by XueqiangChen** [comment]
# 2019年5月6日

## Done
1. 复习Java操作符

## Todo
1. 复习Java控制执行流程
2. Java Foreach语法的原理
3. java switch 是如何支持String进行条件判断的

**Comment by yxg188** [comment]
2019年5月6号

Done

1.提交了死锁的issue
2.学习了String的概述和常用功能：获取和判断。
3.复习了多线程的协作。

ToDo

1.按照视频打字符串的练习。
2.学习String的常用功能：添加，修改，删除
3.学习学习基本数据类对象包装类。

**Comment by yxg188** [comment]
# 2019年5月7号
##Done
1. 学习了String的常见功能：添加，删除，修改。
2. 学习了四个字符串的练习。
##TODO
1. 学习基本数据类型对象包装类。
2. 做发的issue作业。

**Comment by yxg188** [comment]
# 2019年5月8号

## Done
1. 提交了String的issue.
2. 学习了StringBuffer。
3. 学习了基本数据对象包装类。
## TODO
1. 做String的issue。
2. 学习集合框架的概述，共性方法，迭代器。

**Comment by XueqiangChen** [comment]
# 2019年5月9日

## Done

1. 弄清楚 Java foreach 原理
2. 弄清楚 Switch 的语法中如何支持String的

## Todo
1. 第四章的两道练习题：斐波那契数列和吸血鬼数列问题

**Comment by yxg188** [comment]
# 2019年5月9号
## Done
1. 总结了String的常用方法。
2. 学习框架的概述，共性方法。
## TODO
1. 提交issue作业。
2. 学习框架的迭代器， list集合共性的方法。

**Comment by yxg188** [comment]
# 2019年5月10号
## Done
1. 提交了issue。
2。学习了框架的概述，共性方法
## Todo
1. 提交issue。
2 学习框架。

**Comment by yxg188** [comment]
# 2019年5月11号
## Done
1. 提交了issue.
2. 学习的框架的迭代器，List集合共性方法，Listlterator,List集合共性方法。
## Todo
1. 提交issue。
2. 学习框架的Vector中的枚举，LinkedList
3. 做linkedList练习和ArrayList练习。

**Comment by yxg188** [comment]
# 2019年5月12号
## Done
1. 提交issue。
2. 学习框架中的Vector中的枚举，LinkedList
3. 做linkedList练习和ArrayList练习。
## Todo
1. 学习hashset.
2. 学习TreeSet.
3. 学习map共性方法。

**Comment by yxg188** [comment]
# 2019年5月14号
## Done
1. 学习了二叉树。
2。 学习了TreeSet。
3. 学习了comparator方式排序。
## Todo
1. 学习集合框架的泛型概述。
2. 学习泛型的使用，泛型类。

**Comment by XueqiangChen** [comment]
@yxg188 今天完成一下issue

**Comment by XueqiangChen** [comment]
# 2019年5月15日
## Done
1. this 关键字的六种用法以及它在编译时的原理
2. static 关键字的用法与限制，为什么main函数是static的。
3. 垃圾回收初探

## Todo
1. 深入理解Java垃圾回收机制
